# Generated by Django 4.0.3 on 2022-04-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinestock',
            name='drug',
        ),
    ]
