# Generated by Django 4.0.3 on 2022-04-02 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_remove_medicinestock_drug'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinestock',
            name='drug_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pos.drugs'),
        ),
    ]
