# Generated by Django 4.0.3 on 2022-04-06 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_drugs_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugs',
            old_name='category_id',
            new_name='sub_category_id',
        ),
    ]
