# Generated by Django 4.0.3 on 2022-04-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_medicinestock_drug_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinestock',
            name='drug_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.drugs'),
        ),
    ]
