# Generated by Django 4.0.3 on 2022-04-02 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_medicinestock_drug_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='pos.categories'),
        ),
        migrations.AlterField(
            model_name='medicinestock',
            name='drug_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.drugs'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='drug_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.drugs'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.orders'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='pos.categories'),
        ),
    ]
