# Generated by Django 4.0.3 on 2022-04-02 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_drugs_category_id_alter_medicinestock_drug_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='drug_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pos.drugs'),
        ),
    ]
