# Generated by Django 4.0.3 on 2022-04-06 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_drugs_sub_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='sub_category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='pos.subcategory'),
        ),
    ]
