# Generated by Django 4.0.3 on 2022-04-02 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_alter_order_item_drug_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinestock',
            name='drug_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='pos.drugs'),
        ),
    ]
