# Generated by Django 4.0.3 on 2022-04-02 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_medicinestock_drug_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinestock',
            name='drug_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.drugs'),
        ),
    ]
