# Generated by Django 4.0.3 on 2022-04-06 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_drugs_sub_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='pos.categories'),
        ),
    ]
