# Generated by Django 4.0.3 on 2022-04-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_alter_subcategory_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='category_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='pos.categories'),
        ),
    ]
