# Generated by Django 4.0.3 on 2022-04-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_alter_medicinestock_drug_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinestock',
            name='invoice_number',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
