# Generated by Django 4.0.3 on 2022-04-05 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_alter_medicinestock_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.categories'),
        ),
        migrations.AlterField(
            model_name='medicinestock',
            name='invoice_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
