# Generated by Django 4.0.3 on 2022-04-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_alter_drugs_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='drug_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='variant',
            field=models.TextField(),
        ),
    ]
