# Generated by Django 4.0.3 on 2022-05-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_alter_drugs_drug_name_alter_drugs_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinestock',
            name='drug_id',
        ),
        migrations.AddField(
            model_name='medicinestock',
            name='drug_name',
            field=models.TextField(default=None),
        ),
    ]
