# Generated by Django 4.0.3 on 2022-05-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_orders_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='type',
            field=models.TextField(default=None),
        ),
    ]
