# Generated by Django 4.0.3 on 2022-06-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_rename_invoce_number_orders_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='description',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='type',
        ),
        migrations.AddField(
            model_name='orders',
            name='customer_name',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='orders',
            name='remote',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.TextField(default=None),
        ),
    ]
