# Generated by Django 4.0.3 on 2022-06-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_alter_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='updated_at',
        ),
    ]
