# Generated by Django 4.0.3 on 2022-06-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_remove_drugs_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='category_name',
            field=models.TextField(),
        ),
    ]
