# Generated by Django 4.0.3 on 2022-06-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_alter_order_item_drug_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField(unique=True)),
                ('drug_id_id', models.IntegerField()),
                ('value_occurence', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'pharma.sales',
                'managed': False,
            },
        ),
    ]
