# Generated by Django 4.0.3 on 2022-06-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0023_sales'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sales',
            table='sales',
        ),
    ]
