# Generated by Django 4.0.3 on 2022-06-11 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0024_alter_sales_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugs',
            name='category_name',
        ),
        migrations.AddField(
            model_name='drugs',
            name='category_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pos.categories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_item',
            name='drug_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.drugs'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.orders'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
