# Generated by Django 4.0.3 on 2022-06-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_remove_drugs_category_name_drugs_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer_name',
        ),
    ]
